### ISSUE TITLE
DefaultArea wont work if we print text and wait for user input

### ISSUE THREAD

**Issue by xbipin** [pterm/pterm#214]
DefaultArea works generally unless you dont use it for user input using bufio or any other reader, what i was trying to do was create an area and in that print text and wait for user input and when input is fed and not valid wan to replace the old text with an error and ask for it again but it doesnt seem to work making DefaultArea not work at all as intended

**Comment by MarvinJWendt** [comment]
Hi @xbipin, could you please post an example code snippet, of what you're trying to do?

**Comment by xbipin** [comment]
`func CallUserInput(MsgTxt string, rtValue *float64) {
    reader := bufio.NewReader(os.Stdin)
    area, _ := pterm.DefaultArea.Start()
    for {
        area.Update(MsgTxt)
        input, err := reader.ReadString('\n')
        input = strings.TrimSpace(input)
        if err != nil {
        } else {
            *rtValue, err = strconv.ParseFloat(strings.TrimSuffix(input, "\r\n"), 64)
            if err != nil {
            } else {
                break;
            }
        }
    }
    area.Stop()
    CallClear()
    PrintHeader()
    return
}`

**Comment by xbipin** [comment]
```
func CallUserInput(MsgTxt string, rtValue *float64) {
    reader := bufio.NewReader(os.Stdin)
    area, _ := pterm.DefaultArea.Start()
    for {
        area.Update(MsgTxt)
        input, err := reader.ReadString('\n')
        input = strings.TrimSpace(input)
        if err != nil {
        } else {
            *rtValue, err = strconv.ParseFloat(strings.TrimSuffix(input, "\r\n"), 64)
            if err != nil {
            } else {
                break;
            }
        }
    }
    area.Stop()
    CallClear()
    PrintHeader()
    return
}
```

**Comment by MarvinJWendt** [comment]
Hi @xbipin, the `AreaPrinter` doesn't work with user input, that's right. PTerm was meant for plain output, without support for user interactions, but we are currently thinking of ways, how we could implement "Interactive Printers". That would be quite a struggle tho, since the way PTerm is structured, it's hard to implement user input. Specially since we would need to redesign our CI-System to mock user input in the tests and the animation generation.

For what you want to do, you could use https://github.com/atomicgo/cursor, it's also made by myself, and it's what we would use to implement "Interactive Printers" when we do. It gives you full control on handling the cursor movement, clearing lines, etc.

**Comment by MarvinJWendt** [comment]
Interactive Printers are now a thing. Closing this 😉
