### ISSUE TITLE
boxed table - style is not reset between cells

### ISSUE THREAD

**Issue by kjellkvinge** [pterm/pterm#242]
Hi. Thank you for this great project.

I notice that when a cell contains a string formated with style (i.e bold or italic), the next cell is "infected" with the same style. This is only reproducible in boxed mode.

concider the following code:

```go
func TestBox(t *testing.T) {
	line := pterm.Italic.Sprint("italic")


	table, _ := pterm.DefaultTable.WithBoxed().WithData(
		[][]string{
			{line, "a", "b", "c"},
		}).Srender()

	fmt.Println(table)

	table, _ = pterm.DefaultTable.WithData(
		[][]string{
			{line, "a", "b", "c"},
		}).Srender()

	fmt.Println(table)

	pterm.DefaultBox.Println(table)
}

```
I get the following. You can see that the normal table renders fine, but in box-mode - all the rest of the line is italic.

![Screenshot from 2021-07-29 01-43-51](https://user-images.githubusercontent.com/3092520/127410133-0173b365-731e-424d-9462-0245e3dac55d.png)

This is probably a problem with BoxPrinter, as you can see with:

```go
pterm.DefaultBox.Println("normal", pterm.Bold.Sprint("bold."), "this should not be bold\nnewline fixes")
```

Thank you.

**Comment by kjellkvinge** [comment]
A second look, this patch fixes my case, but i probably break something else?

```diff
--- a/box_printer.go
+++ b/box_printer.go
@@ -266,11 +266,11 @@ func (p BoxPrinter) Sprint(a ...interface{}) string {
 	ss := strings.Split(boxString, "\n")
 	for i, s2 := range ss {
 		if runewidth.StringWidth(RemoveColorFromString(s2)) < maxWidth {
-			ss[i] = p.BoxStyle.Sprint(p.VerticalString) + strings.Repeat(" ", p.LeftPadding) + p.TextStyle.Sprint(s2) +
+			ss[i] = p.BoxStyle.Sprint(p.VerticalString) + strings.Repeat(" ", p.LeftPadding) + s2 +
 				strings.Repeat(" ", maxWidth-runewidth.StringWidth(RemoveColorFromString(s2))+p.RightPadding) +
 				p.BoxStyle.Sprint(p.VerticalString)
 		} else {
-			ss[i] = p.BoxStyle.Sprint(p.VerticalString) + strings.Repeat(" ", p.LeftPadding) + p.TextStyle.Sprint(s2) +
+			ss[i] = p.BoxStyle.Sprint(p.VerticalString) + strings.Repeat(" ", p.LeftPadding) + s2 +
 				strings.Repeat(" ", p.RightPadding) + p.BoxStyle.Sprint(p.VerticalString)
 		}
 	}

```

**Comment by MarvinJWendt** [comment]
Hi @kjellkvinge, thanks for the detailed description, and analysis of the issue!

**Comment by MarvinJWendt** [comment]
Quick note: This is a rather critical bug in `Style`. Somehow the styling does not reset, if the text was wrapped in multiple styles:

``go
pterm.Println(pterm.FgDefault.Sprint("test ", pterm.Bold.Sprint("bold"), " not bold"))
```
(also produces wrong output)

**Comment by kjellkvinge** [comment]
Could the bug be in Sprint?

I notice the reset code is replaced by the new style. Now, we keep the reset and add the new style.

```diff
--- a/color.go
+++ b/color.go
@@ -151,7 +151,7 @@ func (c Color) Sprint(a ...interface{}) string {
 	message := Sprint(a...)
 	messageLines := strings.Split(message, "\n")
 	for i, line := range messageLines {
-		messageLines[i] = color.RenderCode(c.String(), strings.ReplaceAll(line, color.ResetSet, Sprintf("\u001B[%sm", c.String())))
+		messageLines[i] = color.RenderCode(c.String(), strings.ReplaceAll(line, color.ResetSet, Sprintf("\u001B[%sm%s",color.ResetSet, c.String())))
 	}
 	message = strings.Join(messageLines, "\n")
 	return message
```
There is a similar line in `func (s Style) Sprint(a ...interface{}) string {`

**Comment by MarvinJWendt** [comment]
Hi @kjellkvinge, yes that's the bug! Sorry for the miscommunication, I already figured out what's causing the bug, I just didn't find any time to fix it yet. I'll look into it in the next couple days.

It's actually quite tricky to fix the issue. The replacement happens so that you can write colored text inside already colored text, without losing the previous color.

For example:

```go
pterm.Println(pterm.Red("Hello " + pterm.Cyan("World") + " !!!"))
```

will print:

![image](https://user-images.githubusercontent.com/31022056/128794806-b70cde11-f814-4622-be87-8ac3952af9b1.png)


Without the replacement, the second color (`LightCyan`) would cancel the first color (`Red`) like this:

![image](https://user-images.githubusercontent.com/31022056/128794858-6660b38d-537e-4990-8982-e72ab1619f9c.png)

Since we cannot (and don't want to) remove this feature, we now have to look for a solution that detects resets from a nested colors and keeps the parent color, but also detects if a user wants to reset a color/style completly. This might end in a lot of refactoring of the current coloring logic.

Me and @floaust already talked about some approaches and we will sit together somewhere in the next days, to find a solution :)

Sorry for the delay, we both are on vacation currently.

**Comment by kjellkvinge** [comment]
No worries. Enjoy you vacation 😃

**Comment by MarvinJWendt** [comment]
Hi @kjellkvinge, you can expect the fix in the next 24h. The bug itself should be fixed now, but I'll do all testing and "release cleanup" later since it's 4 am now :)

I'll update you when everything is out.
Thanks for your patience.

**Comment by MarvinJWendt** [comment]
Hi @kjellkvinge, the fix is now published in [`v0.12.30`](https://github.com/pterm/pterm/releases/tag/v0.12.30).
Thanks for reporting the issue, and let me know if you find something else!

**Comment by kjellkvinge** [comment]
Thank you. The remaining bugs are probably my own 😆 
I'm actually try to make a markdownrenderer using this library. This issue came up with the table component.
I didn't realize that you had this in the pipeline (#14) 
If you are interested I can share what I got. Maybe some of it can be useful for you?

**Comment by MarvinJWendt** [comment]
Sure! You can append a zip in the comments here.
If you want to, you can also work on the existing issue and create the markdown printer in PTerm. I'd be happy to guide you through the process if you have any questions 😉
If not, that wouldn't be a problem, but it might take a while for us to find time to implement it 😅
