### ISSUE TITLE
What is the recommended way to determine whether environment is non-interactive?

### ISSUE THREAD

**Issue by ccremer** [pterm/pterm#274]
So, a run on GitHub with a progressbar produced the following output:
![image](https://user-images.githubusercontent.com/12159026/136715567-769613be-ba13-40eb-be3b-365e13137685.png)

Well, the fact that the next info message is still on the same line, might or might not be a bug.

However, I'm playing anyway with the thought to actually disable the progressbar in a non-interactive environment such as Github actions.
What would be the recommended way to reliably detect this?

**Comment by MarvinJWendt** [comment]
It really depends on the system. Some terminals tell the program that they aren't interactive, but they can still display progressbars etc. That's why we don't check it inside PTerm itself.

If you're just interested in checking if it's running inside a GitHub action, you can check for those environment variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables. The CI variable should most likely be set by most CI systems.

If you just want to check if the output is an actual terminal, you can use something like this: https://github.com/mattn/go-isatty

We also plan to introduce some helper functions here.

**Comment by ccremer** [comment]
Thanks for the reply.
I'd like to stay CI-agnostic in that case and it should also work in Docker containers. https://github.com/mattn/go-isatty sounds good enough, I'll give it try.

**Comment by MarvinJWendt** [comment]
Let me know if you need help :)

**Comment by ccremer** [comment]
This library you mentioned was indeed a good suggestion 👍 
Correctly detects if running on Docker or GH actions :)
