### ISSUE TITLE
Proposal: move all *.go files into a subdirectory.

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#471]
Proposal to Organize Files in Repository Root
Currently, our repository root contains a large number of files, which not only makes the GitHub page cluttered but also obscures the README. To address this issue, I propose that we move PTerm to a subdirectory, specifically /pkg/pterm.

## Breaking Change
It's important to note that this proposed change is significant and will affect every project that uses PTerm if upgraded, as the import path will change. However, the solution is simple, and we can provide a single bash command to update the import path in all files, quickly fixing any affected projects. Given that we are currently in an unstable version (v.0.x.x), now is the perfect time to implement this change, rather than later.

## Priority
Although this issue is not considered a high priority, we will merge it with other breaking changes as soon as they are ready.

**Comment by MarvinJWendt** [comment]
GitHub's new design will display the README at the top and the files in a sidebar. This is no longer needed.

(Yay, no need to break every import path)

**Comment by misitebao** [comment]
Hi @MarvinJWendt 

I'm very supportive of this proposal, but I don't think it should be shut down because of GitHub's new design, because it should be platform-independent. I personally hate having so many code files at the root of a project.

I started a [new proposal](https://github.com/pterm/pterm/issues/516) based on this content and included more content.
