### ISSUE TITLE
If WithFilter is enabled and you try to set a custom key MultiSelect immediately exits.

### ISSUE THREAD

**Issue by croyleje** [pterm/pterm#517]
If you use the the multiselect example code and either enable filter or add a custom key to the example both run and immediately exit out with out allowing user input.

Example with filter enabled.
```package main
import (
	"fmt"

	"atomicgo.dev/keyboard/keys"
	"github.com/pterm/pterm"
)
func main() {
	var options []string

	for i := 0; i < 5; i++ {
		options = append(options, fmt.Sprintf("Option %d", i))
	}

	printer := pterm.DefaultInteractiveMultiselect.WithOptions(options)
	printer.Filter = true
	printer.KeyConfirm = keys.Enter
	printer.KeySelect = keys.Space
	selectedOptions, _ := printer.Show()
	pterm.Info.Printfln("Selected options: %s", pterm.Green(selectedOptions))
}
```

I can also confirm this behavior also occurs if you attempt to add a custom key via the KeySelect or KeyConfirm options to the example MultiSelect code that has filtering enabled by default also.

Jason C.

**Comment by croyleje** [comment]
It appears the issue is with `keys.Space` if you use Tab or any other of the default keys assigned by keyboard/keys.go it seems to work.

**Comment by MarvinJWendt** [comment]
Interesting, thanks for reporting! I'll take a look to fix this as soon as I can.

**Comment by MarvinJWendt** [comment]
Hi, I took a look at it. You're not handling returned errors.

If you modify your code to this:

```go
selectedOptions, err := printer.Show()
pterm.Fatal.PrintOnError(err)
```

this error would occur:
![image](https://github.com/pterm/pterm/assets/31022056/24a9ae0e-ab23-4436-80bc-491cf0078e8a)

---

This behavior is by design. When using the filter function, it is not advisable to combine it with the space character. The reason is that the filter considers any text input, including spaces, which creates ambiguity. If a user types a space, it becomes challenging to determine if they intend to include it as part of the filter or if they are trying to confirm or select something else.

I will update the docs to make this more obvious.
